apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: web
spec:
  type: ExternalName
  externalName: payment.payment.svc.8080.mesh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-api
  namespace: web
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: openid-connect-kong
spec:
  ingressClassName: kong
  rules:
  - host: web-east.local
    http:
      paths:
      - backend:
          service:
            name: payment
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /api/payment