apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: web
spec:
  type: ExternalName
  externalName: ratings.ratings.svc.80.mesh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratings-api
  namespace: web
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: openid-connect-kong
spec:
  ingressClassName: kong
  rules:
  - host: robot-shop-east.kong-sales-engineering.com
    http:
      paths:
      - backend:
          service:
            name: ratings
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /api/ratings