apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: web
spec:
  type: ExternalName
  externalName: catalogue.catalogue.svc.8080.mesh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalogue-api
  namespace: web
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - host: robot-shop-west.kong-sales-engineering.com
    http:
      paths:
      - backend:
          service:
            name: catalogue
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /api/catalogue