apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: web
spec:
  type: ExternalName
  externalName: ratings.ratings.svc.80.mesh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratings-api
  namespace: web
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - host: web-west.local
    http:
      paths:
      - backend:
          service:
            name: ratings
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /api/ratings