apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: web
spec:
  type: ExternalName
  externalName: shipping.shipping.svc.8080.mesh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipping-api
  namespace: web
  annotations:
    konghq.com/strip-path: "true"    
spec:
  ingressClassName: kong
  rules:
  - host: web-west.local
    http:
      paths:
      - backend:
          service:
            name: shipping
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /api/shipping