apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: web
spec:
  type: ExternalName
  externalName: cart.cart.svc.8080.mesh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cart-api
  namespace: web
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - host: web-east.local
    http:
      paths:
      - backend:
          service:
            name: cart
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /api/cart