apiVersion: v1
kind: Secret
metadata:
  name: oidc-config-secret
stringData:
  config: |
    issuer: http://keycloak.kong-sales-engineering.com/auth/realms/kong/.well-known/openid-configuration
    consumer_optional: true
    client_id:
    - $KONG_OIDC_CLIENT_ID
    client_secret:
    - $KONG_OIDC_CLIENT_SECRET
    ssl_verify: false
    consumer_claim:
    - email
    verify_signature: false    
    roles_claim:
    - "realm_access"
    - "roles"  
    session_secret: $KONG_OIDC_SESSION_SECRET
    downstream_id_token_header: Down-Id
    downstream_refresh_token_header: Down-Refresh
    downstream_access_token_header: Down-Access
    upstream_headers_claims:
    - preferred_username
    - email
    upstream_headers_names:
    - x-idp-username
    - x-idp-email
type: Opaque
